"""add slip image option in inventory table

Revision ID: e99df1bcac1d
Revises: dca0de1b72f9
Create Date: 2025-01-05 22:56:44.351025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99df1bcac1d'
down_revision = 'dca0de1b72f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slip_image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('slip_image')

    # ### end Alembic commands ###
